services:
  backend:
    container_name: goalsight-backend
    build: ./backend
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - goalsight-network

  frontend:
    container_name: goalsight-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - goalsight-network

networks:
  goalsight-network:
    driver: bridge 