# Generated by Django 5.2.3 on 2025-06-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("country", models.CharField(max_length=255)),
                ("coach", models.CharField(max_length=255)),
                ("market_value", models.FloatField()),
                ("avg_age", models.FloatField()),
                ("last_5_matches_wdl", models.JSONField()),
                ("xG", models.FloatField()),
                ("ball_possession", models.FloatField()),
                ("shots_on_target", models.IntegerField()),
                ("big_chances_created", models.IntegerField()),
            ],
        ),
    ]
