# Generated by Django 5.2.4 on 2025-07-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_team_buildupplaypassing_team_buildupplayspeed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="logo_url",
            new_name="logo_url_32",
        ),
        migrations.AddField(
            model_name="team",
            name="logo_url_64",
            field=models.URLField(blank=True, null=True),
        ),
    ]
