# Generated by Django 5.2.3 on 2025-07-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_rename_logo_url_team_logo_url_32_team_logo_url_64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="ball_possession",
        ),
        migrations.RemoveField(
            model_name="team",
            name="big_chances_created",
        ),
        migrations.RemoveField(
            model_name="team",
            name="coach",
        ),
        migrations.RemoveField(
            model_name="team",
            name="last_5_matches_wdl",
        ),
        migrations.RemoveField(
            model_name="team",
            name="shots_on_target",
        ),
        migrations.AddField(
            model_name="team",
            name="avg_xGA_last_5",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="team",
            name="avg_xG_last_5",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="team",
            name="days_since_last_game",
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name="team",
            name="drawns_last_5",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="elo_rating",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="team",
            name="glicko2_rating",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="team",
            name="goal_avg_last_5",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="team",
            name="league_strength",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="team",
            name="losses_last_5",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="matches_14_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="team_strength",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="team",
            name="wins_last_5",
            field=models.IntegerField(default=0),
        ),
    ]
