# Generated by Django 5.2.3 on 2025-07-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_remove_team_ball_possession_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="drawns_last_5",
            new_name="draws_last_5",
        ),
        migrations.RemoveField(
            model_name="team",
            name="buildUpPlayPassing",
        ),
        migrations.RemoveField(
            model_name="team",
            name="buildUpPlaySpeed",
        ),
        migrations.RemoveField(
            model_name="team",
            name="chanceCreationCrossing",
        ),
        migrations.RemoveField(
            model_name="team",
            name="chanceCreationPassing",
        ),
        migrations.RemoveField(
            model_name="team",
            name="chanceCreationShooting",
        ),
        migrations.RemoveField(
            model_name="team",
            name="defenceAggression",
        ),
        migrations.RemoveField(
            model_name="team",
            name="defencePressure",
        ),
        migrations.RemoveField(
            model_name="team",
            name="defenceTeamWidth",
        ),
        migrations.RemoveField(
            model_name="team",
            name="xG",
        ),
        migrations.AddField(
            model_name="team",
            name="api_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="avg_shots_on_target_last_5",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="team",
            name="rd",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="team",
            name="volatility",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="team",
            name="avg_age",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="team",
            name="days_since_last_game",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="market_value",
            field=models.FloatField(default=0.0),
        ),
    ]
