# Generated by Django 5.2.3 on 2025-06-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="draw",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
