# Generated by Django 5.2.3 on 2025-07-19 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_alter_match_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="draw",
        ),
    ]
