name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    # Remove working-directory so all commands run from repo root

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      # Install docker-compose
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
        
      # Use docker-compose to build and run backend and db
      - name: Build and start backend and db containers
        run: |
          docker-compose -f docker-compose.prod.yml up -d --build
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      
      - name: Wait for backend DB to be ready
        run: |
          timeout 60 bash -c 'until docker-compose -f docker-compose.prod.yml exec -T postgres pg_isready -U $DATABASE_USER -d $DATABASE_NAME; do sleep 2; done'
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Run migrations
        run: |
          docker-compose -f docker-compose.prod.yml exec -T backend python goalsight/manage.py migrate
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}

      - name: Run backend tests
        run: |
          docker-compose -f docker-compose.prod.yml exec -T backend python goalsight/manage.py test
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}

      - name: Stop containers
        if: always()
        run: |
          docker-compose -f docker-compose.prod.yml down


  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run component tests
        run: npm run test:components || echo "Component tests failed but continuing..."
        
      - name: Run API integration tests
        run: npm run test:api || echo "API integration tests failed but continuing..."
        continue-on-error: true
        
      - name: Run end-to-end tests
        run: npm run test:e2e || echo "E2E tests failed but continuing..."
        continue-on-error: true
        
      - name: Generate coverage for components
        run: npm run test:coverage:components || echo "Component coverage failed but continuing..."
        continue-on-error: true
        
      - name: Generate coverage for API integration
        run: npm run test:coverage:api || echo "API coverage failed but continuing..."
        continue-on-error: true
        
      - name: Lint
        run: npm run lint || echo "Lint errors (not failing build)"
        continue-on-error: true
